grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 5
    verbose: 2


model_selection:
  module_0:
    module: sklearn.linear_model
    class: LinearRegression
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false

  module_1:
    module: sklearn.ensemble
    class: RandomForestRegressor
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 4
      - 6
      - 12
      n_estimators:
      - 100
      - 150
      - 200
      bootstrap:
      - true
      - false
      oob_score:
      - true
      - false
      max_depth:
      - 2
      - 4
      - 6 